### PR TITLE
Fix 'bal dist pull' failure in windows

### LINKED ISSUE #382: 'bal dist pull <VERSION>' command fails in Windows when pulling a new JRE version along with distribution
### Description

`bal dist pull <VERSION>` command fails in Windows when pulling a new JRE version along with distribution. This happens when we run the command in the `Command Prompt` with administrator permissions.

```
$ bal dist pull 2201.9.0
Checking for newer versions of the update tool...
Fetching the '2201.9.0' distribution from the remote server...
Downloading 2201.9.0 100% [==========================================================] 191/191 MB (0:00:21 / 0:00:00)

Fetching the dependencies for '2201.9.0' from the remote server...
Downloading jdk-17.0.7+7-jre 100% [====================================================] 42/42 MB (0:00:03 / 0:00:00)

ballerina: permission denied: you do not have write access to 'C:\Program Files\Ballerina\dependencies\jdk-17.0.7+7-jre'
```

### Steps to Reproduce

Run the `bal dist pull <VERSION>` command in Command Prompt which will pull a version of Ballerina that uses different Java version than the current version.

### Version

Update tool version: all

### Environment Details (with versions)

Affective OS : Windows

### PR DESCRIPTION
**Pull request by NipunaMadhushan**
## Purpose
This will solve the executable permission set for dependency jre folder when a new jre version is pulled along with `bal dist pull <VERSION>` command.

Fixes #382

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: src/main/java/org/ballerinalang/command/util/ToolUtil.java [hunk 1]
```diff
@@ -1033,8 +1033,14 @@ public static String encodePlusCharacters(String dependency) {
...
         try {
-            process = Runtime.getRuntime().exec("chmod -R 755 " + filePath);
-            process.waitFor();
+            if (OSUtils.isWindows()) {
+                process = Runtime.getRuntime().exec("icacls " + filePath + " /grant Everyone:(OI)(CI)RX /T");
+                process.waitFor();
+            }
+            else {
+                process = Runtime.getRuntime().exec("chmod -R 755 " + filePath);
+                process.waitFor();
```
Comment (keizer619) [inline src/main/java/org/ballerinalang/command/util/ToolUtil.java:1042]: Lets take waitfor outside

Comment (NipunaMadhushan) [reply src/main/java/org/ballerinalang/command/util/ToolUtil.java]: @keizer619 addressed review suggestions

**Review by keizer619 — APPROVED** [review]
