### PR TITLE
Fix support for additional arguments in DefaultCommand

### LINKED ISSUE #309: Unmatched argument log is printed in bal commands with `--help` flag
**Description:**
In some `bal --help <cmd-name>` commands, after the help text, an error `Unmatched argument at index 1:` is printed

**Steps to reproduce:**
```
$ bal --help openapi
NAME
       ballerina-openapi - Generate a Ballerina service or a client from an
       ... ELIMINATED FOR BREVITY
      Unmatched argument at index 1: 'openapi'
```

**Affected Versions:**
2201.7.0 (need to check in other versions as well)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Jaagrav**
## Purpose
In some bal --help <cmd-name> commands, after the help text, an error Unmatched argument at index 1: is printed

## Goals
Get rid of the error that was caused due to the default command not expecting additional arguments

## Approach
Add a `CommandLine.Parameters` such that we can take in a list of parameters avoiding the error and maybe put it to use in the future instead of modify the bal shell file

## User stories
When I first found out about ballerina and started tinkering with it, I ran into this error as well, it didn't make sense to me, and neither did I think it was actually a bug, but when I found this issue, I was relieved cause I spent quite some time trying to figure out how am I typing a `--help` command wrong. XD

## Release note
Fix unmatched argument log when running --help

Closes #309

### CODE REVIEW

**Comment by Jaagrav** [comment]
Hi @keizer619 PTAL at the changes and lmk if it's the right way to solve this issue?

**Comment by Jaagrav** [comment]
Hey @keizer619 any updates here?

File: src/main/java/org/ballerinalang/command/cmd/DefaultCommand.java [hunk 1]
```diff
@@ -37,12 +38,15 @@ public class DefaultCommand extends Command implements BCommand {
...
+    @CommandLine.Parameters(description = "Help command name")
+    private List<String> helpCommands;
+
     public DefaultCommand(PrintStream printStream) {
         super(printStream);
     }
 
     @Override
-    public void execute() {
+    public void execute() {
```
Comment (gayaldassanayake) [inline src/main/java/org/ballerinalang/command/cmd/DefaultCommand.java:49]:
```suggestion
    public void execute() {
```

**Comment by gayaldassanayake** [comment]
I tested and it is working. However had an offline discussion with @keizer619 and I'm not sure if we should support `bal --help` with additional args. @keizer619 WDYT?

**Comment by Jaagrav** [comment]
Any update here? @gayaldassanayake @keizer619 ?

**Review by keizer619 — APPROVED** [review]
